# Generated by Django 5.2.15 on 2026-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_read_communication_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
