# Generated by Django 5.2.15 on 2026-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_campaign_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='churn_risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Churn risk computed from recency: >180d=high, 90-180d=medium, <90d=low.', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='clv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Customer Lifetime Value = total spend in INR.', max_digits=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='olist_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_frequency',
            field=models.PositiveIntegerField(default=0, help_text='Total number of orders placed.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_monetary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average order value in INR.', max_digits=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_recency',
            field=models.PositiveIntegerField(default=0, help_text='Days since last order. Lower = more recent.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Composite RFM quintile score 1-5 (5 = best).'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='olist_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total payment captured from Olist payments CSV, stored in INR.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Customer review score 1–5 from Olist reviews CSV.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_amount_brl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount in BRL from Olist dataset. NULL for non-Olist orders.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='is_prebuilt',
            field=models.BooleanField(default=False, help_text='True for the 5 Olist-derived prebuilt segments.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Order amount in INR (= source_amount_brl × BRL_TO_INR_RATE for Olist data).', max_digits=14),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['rfm_score'], name='crm_customer_rfm_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['churn_risk'], name='crm_customer_churn_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['clv'], name='crm_customer_clv_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['olist_order_id'], name='crm_order_olist_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['is_prebuilt'], name='crm_segment_prebuilt_idx'),
        ),
    ]
