# Generated by Django 5.2.15 on 2026-06-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_olist_rfm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='expected_outcome',
            field=models.JSONField(blank=True, help_text='Predicted reach, engagement, conversion, and revenue from AI Copilot.', null=True),
        ),
    ]
