/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AudiencesRouteImport } from './routes/audiences'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiencesRoute = AudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/copilot': typeof CopilotRoute
  '/customers': typeof CustomersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/customers/$id': typeof CustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/copilot': typeof CopilotRoute
  '/customers': typeof CustomersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/customers/$id': typeof CustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/copilot': typeof CopilotRoute
  '/customers': typeof CustomersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/customers/$id': typeof CustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audiences'
    | '/campaigns'
    | '/copilot'
    | '/customers'
    | '/settings'
    | '/campaigns/$id'
    | '/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audiences'
    | '/campaigns'
    | '/copilot'
    | '/customers'
    | '/settings'
    | '/campaigns/$id'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audiences'
    | '/campaigns'
    | '/copilot'
    | '/customers'
    | '/settings'
    | '/campaigns/$id'
    | '/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AudiencesRoute: typeof AudiencesRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  CopilotRoute: typeof CopilotRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiences': {
      id: '/audiences'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AudiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsIdRoute: typeof CampaignsIdRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIdRoute: CampaignsIdRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AudiencesRoute: AudiencesRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  CopilotRoute: CopilotRoute,
  CustomersRoute: CustomersRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
