/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AudiencesRouteImport } from './routes/audiences'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiencesRoute = AudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audiences': typeof AudiencesRoute
  '/copilot': typeof CopilotRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audiences': typeof AudiencesRoute
  '/copilot': typeof CopilotRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audiences': typeof AudiencesRoute
  '/copilot': typeof CopilotRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audiences'
    | '/copilot'
    | '/settings'
    | '/campaigns/$id'
    | '/customers/$id'
    | '/campaigns/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audiences'
    | '/copilot'
    | '/settings'
    | '/campaigns/$id'
    | '/customers/$id'
    | '/campaigns'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audiences'
    | '/copilot'
    | '/settings'
    | '/campaigns/$id'
    | '/customers/$id'
    | '/campaigns/'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AudiencesRoute: typeof AudiencesRoute
  CopilotRoute: typeof CopilotRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiences': {
      id: '/audiences'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AudiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AudiencesRoute: AudiencesRoute,
  CopilotRoute: CopilotRoute,
  SettingsRoute: SettingsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
